config/routes.rb
Rails.application.routes.draw do
  get 'grouplist/new'
  get 'grouplist/edit'
  get 'list/new'
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
}
  root 'top#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups do
    resources :grouplist do
      resources :groupcard
    end
  end

  resources :list, only: [:new, :create, :edit, :update, :destroy]do
    resources :card, expect: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list

  validates :title, length: { in: 1..255 }
  validates :memo, length: { maximum: 1000 }

  enum status: %w(新規 作業中 完了)
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy
  has_many :grouplists, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { in: 1..255 }

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/groupcard.rb
class Groupcard < ApplicationRecord
  belongs_to :grouplist

  validates :title, length: { in: 1..255 }
  validates :memo, length: { maximum: 1000 }

  enum status: %w(新規 作業中 完了)
end

app/models/grouplist.rb
class Grouplist < ApplicationRecord

  validates :title, length: { in: 1..255 }

  belongs_to :user
  belongs_to :group
  has_many :groupcards, dependent: :destroy

end

app/models/list.rb
class List < ApplicationRecord

  validates :title, length: { in: 1..255 }

  belongs_to :user
  has_many :cards, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :omniauthable, omniauth_providers: %i(facebook twitter google)

         def self.from_omniauth(auth)
          where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.name = auth.info.name
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
          end
        end

  validates :name, presence: true, length: { maximum: 20 }

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :lists, dependent: :destroy
  has_many :grouplists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :set_card, only: %i( show edit update destroy)

  def index
  end

  def new
    @card = Card.new
    @list = List.find_by(id: params[:list_id])
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to :root
    else
      render action: :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @card.update_attributes(card_params)
      redirect_to :root
    else
      render action: :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to :root
  end

  private

  def card_params
    params.require(:card).permit(:title, :memo, :status, :list_id)
  end

  def set_card
    @card = Card.find_by(id: params[:id])
  end
end

app/controllers/groupcard_controller.rb
class GroupcardController < ApplicationController
  before_action :set_groupcard, only: %i( show edit update destroy)
  before_action :set_grouplist, only: %i( new create show edit update destroy )

  layout 'group'

  def new
    @groupcard = Groupcard.new
  end

  def create
    @groupcard = Groupcard.new(groupcard_params)
    if @groupcard.save
      redirect_to group_path(@grouplist.group_id)
    else
      render action: :new
    end
  end

  def show
  end

  def update
    if @groupcard.update_attributes(groupcard_params)
      redirect_to group_path(@grouplist.group_id)
    else
      render action: :edit
    end
  end

  def destroy
    @groupcard.destroy
    redirect_to group_path(@grouplist.group_id,@grouplist)
  end



  private

  def groupcard_params
    params.require(:groupcard).permit(:title, :memo, :status, :grouplist_id)
  end

  def set_groupcard
    @groupcard = Groupcard.find_by(id: params[:id])
  end

  def set_grouplist
    @grouplist = Grouplist.find(params[:grouplist_id])
  end
end

app/controllers/grouplist_controller.rb
class GrouplistController < ApplicationController
  before_action :set_group, only: %i( new create edit update )
  before_action :set_grouplist, only: %i( edit update destroy )

  layout 'group'

  def index
  end

  def new
    @grouplist = Grouplist.new
    # @grouplists = @group.grouplist.includes(:user)
  end

  def create
    @grouplist = @group.grouplists.new(grouplist_params)
    if @grouplist.save
      redirect_to group_path(@group)
    else
      render action: :new
    end
  end

  def show
    @grouplists = Grouplist.find(params[:id]).order("created_at ASC")
  end

  def edit
  end

  def update
    if @grouplist.update_attributes(grouplist_params)
      redirect_to group_path(@group)
    else
      render action: :edit
    end
  end

  def destroy
    @grouplist.destroy
    redirect_to group_path(@grouplist.group_id)
  end

  private

    def grouplist_params
      params.require(:grouplist).permit(:title).merge(user_id: current_user.id)
    end

    def set_group
      @group = Group.find(params[:group_id])
    end

    def set_grouplist
      @grouplist = Grouplist.find(params[:id])
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i( show edit update destroy)

  layout 'group'

  def index
  end


  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to groups_path, notice: 'グループを作成しました'
    else
      render action: :new
    end
  end

  def show
    @groups = Group.all
    @grouplists = Grouplist.where(user: current_user, group: @group).order("created_at ASC")
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path(@group), notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path, alert: 'グループを削除しました'
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController

  before_action :set_list, only: [:edit, :update, :destroy]

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to :root
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @list.update_attributes(list_params)
      redirect_to :root
    else
      render action: :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to :root
  end

  private

    def list_params
      params.require(:list).permit(:title).merge(user: current_user)
    end

    def set_list
      @list = List.find(params[:id])
    end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    @lists = List.where(user: current_user).order("created_at ASC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/groupcard_helper.rb
module GroupcardHelper
end

app/helpers/grouplist_helper.rb
module GrouplistHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/card/edit.html.haml
.cardeditPgae
  - if @card.errors.any?
    %p.alert タイトルは1～255文字以内で入力してください
  .container
    = form_with model: @card, url: { action: :update }, html: { class: 'cardeditForm' }, local: true do |f|
      .cardeditForm_title
        = f.label :title
        = f.text_field :title, class: "form-control", placeholder: "カード名"
      .cardeditForm_memo
        = f.label :memo
        = f.text_area :memo, class: "form-control", placeholder: "詳細"
      .cardeditForm_status
        = f.label :status, class: "cardeditForm_status_label"
        = f.select :status, Card.statuses.keys, class: "cardeditForm_status_select"
      .text-center= f.submit "更新する", class: "submitBtn"

app/views/card/new.html.haml
.cardnewPgae
  - if @card.errors.any?
    %p.alert タイトルは1～255文字以内で入力してください
  .container
    = form_with model: @card, url: { action: :create }, html: { class: 'cardnewForm' }, local: true do |f|
      = f.hidden_field :list_id, value: @list.id
      .cardnewForm_title
        = f.label :title
        = f.text_field :title, autofocus: true, class: "form-control", placeholder: "カード名"
      .cardnewForm_memo
        = f.label :memo
        = f.text_area :memo, autofocus: true, class: "form-control", placeholder: "詳細"
      .text-center= f.submit "作成する", class: "submitBtn"

app/views/card/show.html.haml
.carddetailPage
  .container
    .cardContents
      .cardContents_title
        %div タイトル
        %h3= @card.title
      .cardContents_memo
        %div メモ
        %div= @card.memo
      .cardContents_listStatus
        %div リスト名
        %div= @card.list.title
      .cardContents_listStatus
        %div ステータス
        %div= @card.status
      .cardContents_btnArea
        = link_to '編集する', edit_list_card_path(@card.list, @card), class: "edit_btn"
        = link_to '削除', list_card_path(@card.list, @card), class: "text-danger delete_btn", method: :delete, data: { confirm: "このカードを削除して大丈夫ですか?" }

app/views/groupcard/edit.html.haml
.cardeditPgae
  - if @groupcard.errors.any?
    %p.alert タイトルは1～255文字以内で入力してください
  .container
    = form_with model: @groupcard, url: { action: :update }, html: { class: 'cardeditForm' }, local: true do |f|
      .cardeditForm_title
        = f.label :title
        = f.text_field :title, class: "form-control", placeholder: "カード名"
      .cardeditForm_memo
        = f.label :memo
        = f.text_area :memo, class: "form-control", placeholder: "詳細"
      .cardeditForm_status
        = f.label :status, class: "cardeditForm_status_label"
        = f.select :status, Card.statuses.keys, class: "cardeditForm_status_select"
      .text-center= f.submit "更新する", class: "submitBtn"

app/views/groupcard/new.html.haml
.cardnewPgae
  - if @groupcard.errors.any?
    %p.alert タイトルは1～255文字以内で入力してください
  .container
    = form_with model: @groupcard, url: { action: :create }, html: { class: 'cardnewForm' }, local: true do |f|
      = f.hidden_field :grouplist_id, value: @grouplist.id
      .cardnewForm_title
        = f.label :title
        = f.text_field :title, autofocus: true, class: "form-control", placeholder: "カード名"
      .cardnewForm_memo
        = f.label :memo
        = f.text_area :memo, autofocus: true, class: "form-control", placeholder: "詳細"
      .text-center= f.submit "作成する", class: "submitBtn"

app/views/groupcard/show.html.haml
%h2 Details
.carddetailPage
  .container
    .cardContents
      .cardContents_title
        %div タイトル
        %h3= @groupcard.title
      .cardContents_memo
        %div メモ
        %div= @groupcard.memo
      .cardContents_listStatus
        %div リスト名
        %div= @groupcard.grouplist.title
      .cardContents_listStatus
        %div ステータス
        %div= @groupcard.status
      .cardContents_btnArea
        = link_to '編集する', edit_group_grouplist_groupcard_path(@grouplist.group_id, @grouplist, @groupcard), class: "edit_btn"
        = link_to '削除', group_grouplist_groupcard_path(@grouplist.group_id, @grouplist, @groupcard), class: "text-danger delete_btn", method: :delete, data: { confirm: "このカードを削除して大丈夫ですか?" }

app/views/grouplist/edit.html.haml
.listeditPage
  - if @grouplist.errors.any?
    %p.alert タイトルは1〜255文字内で入力して下さい
  .container
    = form_with model: @grouplist, url: { action: :update }, html: { class: 'listForm' }, local: true do |f|
      = f.label :title
      = f.text_field :title, class: "form-control  listName", placeholder: "リスト名"
      .text-center= f.submit "編集する", class: "submitBtn"

app/views/grouplist/new.html.haml
.listnewPage
  - if @grouplist.errors.any?
    %p.alert タイトルは1～255文字以内で入力してください
  = form_with model: @grouplist, url: { action: :create }, class: "container", local: true do |f|
    = f.label :title
    = f.text_field :title, autofocus: true, class: "form-control listName", placeholder: "リスト名"
    .text-center= f.submit "作成", class: "submitBtn"

app/views/groups/edit.html.haml
= form_with model: @group, url: { action: :update }, class: "container", local: true do |f|
  = f.label :group
  = f.hidden_field :id, value: @group.id
  = f.text_field :name, autofocus: true, class: "form-control listName", placeholder: "グループ名"
  .chat-group-form__field
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_メンバーを追加"} メンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.form-control{:placeholder => "ユーザー名を入力してください", :type => "text"}/
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_メンバー"} Member
    .chat-group-form__field--right
      #chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
          %p.chat-group-user__name= current_user.name

        - @group.users.each do |user|
          - if current_user.name != user.name
            .chat-group-user.clearfix.js-chat-member
              %input{name: "group[user_ids][]", type: "hidden", value: user.id}
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除
              %p.chat-group-user__name
                = user.name


  .text-center= f.submit "更新する", class: "submitBtn"

app/views/groups/index.html.haml
.groups
  %h3 Groups
.container_group
  - current_user.groups.each do |group|
    %ul
      .show_link
        = link_to group_path(group) do
          %li= group.name
      .list_group_action
        .list_group_action_member
          %li.member
            %p :Member
          - group.users.each do |user|
            %li
              %p :
            %li
              %p= user.name
        .list_group_action_fas
          = link_to content_tag(:i, '', class: 'fas fa-trash'), group, method: :delete, data: { confirm: "#{group.name}を削除して大丈夫ですか？" }
          = link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_group_path(group))

app/views/groups/new.html.haml
= form_with model: @group, url: { action: :create }, class: "container", local: true do |f|
  = f.label :Group
  = f.hidden_field :id, value: @group.id
  = f.text_field :name, autofocus: true, class: "form-control listName", placeholder: "グループ名"
  .chat-group-form__field
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_メンバーを追加"} メンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.form-control{:placeholder => "ユーザー名を入力してください", :type => "text"}/
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_メンバー"} Member
    .chat-group-form__field--right
      #chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
          %p.chat-group-user__name= current_user.name

        - @group.users.each do |user|
          - if current_user.name != user.name
            .chat-group-user.clearfix.js-chat-member
              %input{name: "group[user_ids][]", type: "hidden", value: user.id}
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除
              %p.chat-group-user__name
                = user.name


  .text-center= f.submit "作成する", class: "submitBtn"

app/views/groups/show.html.haml
.groups
  .container_group
    %h4.show_link_group= @group.name
    .list_group_action
      .list_group_action_member
        - @group.users.each do |user|
          %p :
          %p= user.name
      .list_group_action_fas
        = link_to "new Task", new_group_grouplist_path(@group.id), class: "nav-link listNew"
.topPage
  .listWrapper
    - @group.grouplists.each do |grouplist|
      .list
        .list_header
          %h3.list_header_title= grouplist.title
          .list_header_action
            = link_to content_tag(:i, '', class: 'fas fa-trash'), group_grouplist_path(grouplist.group_id, grouplist), method: :delete, data: { confirm: "#{grouplist.title}を削除して大丈夫ですか？" }
            = link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_group_grouplist_path(@group.id, grouplist))
        .cardWrapper
          - grouplist.groupcards.each do |groupcard|
            = link_to group_grouplist_groupcard_path(grouplist.group_id, grouplist, groupcard), class:"cardDetail_link" do
              .card
                %h3.card_title= groupcard.title
                .card_memo
                  .card_status= groupcard.status
                  - if groupcard.memo.size > 8
                    .card_detail.is-exist
                      %i.fas.fa-bars
                  - else
                    .card_detail.is-exist= groupcard.memo
          .addCard
            %i.far.fa-plus-square
            = link_to "さらにカードを追加", new_group_grouplist_groupcard_path(@group.id, grouplist), class: "addCard_link"

app/views/list/edit.html.haml
.listeditPage
  - if @list.errors.any?
    %p.alert タイトルは1〜255文字内で入力して下さい
  .container
    = form_with model: @list, url: { action: :update }, html: { class: 'listForm' }, local: true do |f|
      = f.label :title
      = f.text_field :title, class: "form-control  listName", placeholder: "リスト名"
      .text-center= f.submit "編集する", class: "submitBtn"

app/views/list/new.html.haml
.listnewPage
  - if @list.errors.any?
    %p.alert タイトルは1～255文字以内で入力してください
  = form_with model: @list, url: { action: :create }, class: "container", local: true do |f|
    = f.label :title
    = f.text_field :title, autofocus: true, class: "form-control listName", placeholder: "リスト名"
    .text-center= f.submit "作成", class: "submitBtn"