config/routes.rb
Rails.application.routes.draw do
  get 'grouplist/new'
  get 'grouplist/edit'
  get 'list/new'
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
}
  root 'top#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups do
    resources :grouplist do
      resources :groupcard
    end
  end

  resources :list, only: [:new, :create, :edit, :update, :destroy]do
    resources :card, expect: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list

  validates :title, length: { in: 1..255 }
  validates :memo, length: { maximum: 1000 }

  enum status: %w(新規 作業中 完了)
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy
  has_many :grouplists, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { in: 1..255 }

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/groupcard.rb
class Groupcard < ApplicationRecord
  belongs_to :grouplist

  validates :title, length: { in: 1..255 }
  validates :memo, length: { maximum: 1000 }

  enum status: %w(新規 作業中 完了)
end

app/models/grouplist.rb
class Grouplist < ApplicationRecord

  validates :title, length: { in: 1..255 }

  belongs_to :user
  belongs_to :group
  has_many :groupcards, dependent: :destroy

end

app/models/list.rb
class List < ApplicationRecord

  validates :title, length: { in: 1..255 }

  belongs_to :user
  has_many :cards, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :omniauthable, omniauth_providers: %i(facebook twitter google)

         def self.from_omniauth(auth)
          where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.name = auth.info.name
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
          end
        end

  validates :name, presence: true, length: { maximum: 20 }

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :lists, dependent: :destroy
  has_many :grouplists, dependent: :destroy
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :set_card, only: %i( show edit update destroy)

  def index
  end

  def new
    @card = Card.new
    @list = List.find_by(id: params[:list_id])
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to :root
    else
      render action: :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @card.update_attributes(card_params)
      redirect_to :root
    else
      render action: :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to :root
  end

  private

  def card_params
    params.require(:card).permit(:title, :memo, :status, :list_id)
  end

  def set_card
    @card = Card.find_by(id: params[:id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i( show edit update destroy)

  layout 'group'

  def index
  end


  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to groups_path, notice: 'グループを作成しました'
    else
      render action: :new
    end
  end

  def show
    @groups = Group.all
    @grouplists = Grouplist.where(user: current_user, group: @group).order("created_at ASC")
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path(@group), notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path, alert: 'グループを削除しました'
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController

  before_action :set_list, only: [:edit, :update, :destroy]

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to :root
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @list.update_attributes(list_params)
      redirect_to :root
    else
      render action: :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to :root
  end

  private

    def list_params
      params.require(:list).permit(:title).merge(user: current_user)
    end

    def set_list
      @list = List.find(params[:id])
    end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    @lists = List.where(user: current_user).order("created_at ASC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/groupcard_helper.rb
module GroupcardHelper
end

app/helpers/grouplist_helper.rb
module GrouplistHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Task Management
    = csrf_meta_tags
    = csp_meta_tag
    %link{:href => "https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Montserrat", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
%body
  = render 'top/header'
  - if flash[:notice]
    .notice
      = flash[:notice]
  - if flash[:alert]
    .alert
      = flash[:alert]
  = yield

app/views/layouts/group.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Task Management Group
    = csrf_meta_tags
    = csp_meta_tag
    %link{:href => "https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Montserrat", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %header.header
    %nav.nav
      %ul.header_menu
        %li.header_menu_title= link_to "Task Management", root_path, class: "nav-link"
        - if user_signed_in?
          %li.nav-link= current_user.name
        %li
          %ul.header_menu_inner
            %li= link_to "グループ一覧", groups_path, class: "nav-link groupNew"
            %li= link_to "グループ作成", new_group_path, class: "nav-link listNew"
            %li= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link"


  - if flash[:notice]
    .notice
      = flash[:notice]
  - if flash[:alert]
    .alert
      = flash[:alert]
= yield

app/views/layouts/groups.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Task Management Group
    = csrf_meta_tags
    = csp_meta_tag
    %link{:href => "https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Montserrat", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %header.header
    %nav.nav
      %ul.header_menu
        %li.header_menu_title= link_to "Task Management", root_path, class: "nav-link"
        - if user_signed_in?
          %li.nav-link= current_user.name
        %li
          %ul.header_menu_inner
            %li= link_to "グループ一覧", groups_path, class: "nav-link groupNew" if current_user
            %li= link_to "グループリスト作成", new_list_path, class: "nav-link listNew" if current_user
            %li= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" if current_user


  - if flash[:notice]
    .notice
      = flash[:notice]
  - if flash[:alert]
    .alert
      = flash[:alert]
= yield